import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        display: ['"Cormorant Garamond"', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['"DM Mono"', 'monospace'],
      },
      colors: {
        border:     "hsl(var(--border))",
        input:      "hsl(var(--input))",
        ring:       "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // Brand palette
        ink:     { DEFAULT: 'var(--ink)', 2: 'var(--ink-2)' },
        void:    'var(--void)',
        deep:    'var(--deep)',
        surface: { DEFAULT: 'var(--base)', 1: 'var(--surface-1)', 2: 'var(--surface-2)', 3: 'var(--surface-3)' },
        obsidian: 'var(--ink)',
        gold:     { DEFAULT: 'var(--gold)', mid: 'var(--gold-mid)', bright: 'var(--gold-bright)', dim: 'var(--gold-dim)', light: 'var(--gold-bright)' },
        rose:     { DEFAULT: 'var(--rose)', mid: 'var(--rose-mid)', bright: 'var(--rose-bright)', dim: 'var(--rose-dim)' },
        violet:   { DEFAULT: 'var(--violet)', mid: 'var(--violet-mid)', dim: 'var(--violet-dim)' },
        teal:     { DEFAULT: 'var(--teal)', mid: 'var(--teal-mid)', dim: 'var(--teal-dim)' },
        mint:     { DEFAULT: 'var(--teal)' },
        // Shadcn tokens
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))" },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))" },
        primary:     { DEFAULT: "hsl(var(--primary))",     foreground: "hsl(var(--primary-foreground))" },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))" },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-up":        { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "shimmer":        { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "glow-pulse":     { "0%, 100%": { opacity: "0.4" }, "50%": { opacity: "1" } },
        "dotPulse":       { "0%, 100%": { opacity: "0.25", transform: "scale(1)" }, "50%": { opacity: "1", transform: "scale(1.5)" } },
        "auroraDrift":    { from: { transform: "translate(0,0) scale(1)" }, to: { transform: "translate(4%,4%) scale(1.08)" } },
        "float":          { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
        "pulseRing":      { "0%": { transform: "scale(1)", opacity: "0.6" }, "100%": { transform: "scale(1.5)", opacity: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-up":        "fade-up 0.6s ease-out",
        "shimmer":        "shimmer 2.2s linear infinite",
        "glow-pulse":     "glow-pulse 2s ease-in-out infinite",
        "float":          "float 3.5s ease-in-out infinite",
        "pulse-ring":     "pulseRing 2s ease-out infinite",
        "aurora":         "auroraDrift 9s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
